#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
##  redis:
##    host: 0.0.0.0
##    port: 6379
##  cache:
##    type: redis
##    cache-names:
##    - Recipe
#  r2dbc:
#    url: r2dbc:h2:mem:omnicell
#    username: sa
#    password: password
recipe:
  url: https://s3-ap-southeast-1.amazonaws.com/he-public-data/reciped9d7b8c.json